apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic-expense-claim
  namespace: expense
spec:
  accessModes:
  - ReadWriteOnce 
  resources:
    requests:
      storage: 4Gi
  storageClassName: "expense-ebs"
